### ISSUE TITLE
Got fwg

### ISSUE THREAD

**Issue by zhijianggamer** [noatpad/wow-your-friends#33]
So happy to be one of the called  'celeste gods'.It is hard to imagine that it is possible to get from the beginning.Thanks the campany for making so good a game,and the company of all the celeste players.
vedio:
https://youtu.be/PkRstMjHOwk?si=5wGGHEidooNZevsL

**Comment by zhijianggamer** [comment]
Is it valid for the 202 list?

**Comment by noatpad** [comment]
Hi! Pardon the delay on this, but I just checked the video and it looks all good! I can add you to the list, though you will be listed under the "Show runs with DTS" checkbox since you performed the Dash Trigger Skip.

I also noticed that this berry was the 201st berry to be collected, not the 202nd one. So this will also be marked as a non-202 run as well! Unless you did get the berry before (or you get it in the future), send over a picture of the journal with it or anything that proves you have all 202 berries and I'll update your entry!

For the time being, I'm gonna add you in the list shortly! Congrats!
